apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elba.fullname" . }}
data:
  elba.toml: |
{{- if .Values.elbaConfig }}
{{ (.Values.elbaConfig | toToml | indent 4) }}
{{- else }}
{{ .Files.Get "elba.toml" | indent 4 }}
{{- end }}
